box         = 'precise64'
url         = 'https://cloud-images.ubuntu.com/vagrant/precise/current/precise-server-cloudimg-amd64-vagrant-disk1.box'
hostname    = 'mysql'
domain      = 'testing.com'
ip_address  = '192.168.0.45'
ram         = '512'

Vagrant.configure("2") do |config|
  config.vm.box = box
  config.vm.box_url = url
  config.vm.hostname = hostname + '.' + domain
  config.vm.network "private_network", ip: ip_address
  config.vm.network "forwarded_port", guest: 3306, host: 3306
  config.vm.network "forwarded_port", guest: 80, host: 3307 

  config.vm.provider "virtualbox" do |vb|
    vb.customize [
      'modifyvm', :id,
      '--name', hostname,
      '--memory', ram
    ]
  end

  config.vm.provision :shell, :inline => "[ -f /tmp/updated ] || apt-get update && touch /tmp/updated"
  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = 'puppet/manifests'
    puppet.manifest_file = 'site.pp'
    puppet.module_path = 'puppet/modules'
    puppet.options = "--verbose"
  end

  config.vm.provision :shell, :inline => "reboot"
  config.vm.provision :shell, :inline => "[ -f /vagrant/machine-details ] && cat /vagrant/machine-details"

end

